baseURL = "https://cosmiccheerleader.co.uk/"
#baseURL = "https://brave-fermat-0bfb8a.netlify.app/"
#baseURL = "https://localhost.com"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

defaultContentLanguage = "en"

[languages]
    [languages.navigation]
    help = "Help"
    
    [languages.en]
    languageName = "English"
    # The "title" of your website
    title = "Sandrine Marquet - Tarot & Magic"
    weight = 1
    
  [languages.fr]
    languageName = "Francais"
    title = "Sandrine Marquet - Divinatrice & tireuse de cartes"
    weight = 2
 #   staticDir = "static/en"
  [languages.fr.navigation]
    help = "Aide"
    
#[permalinks]
#    posts = "/:section/:slug/"

[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© S Marquet"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Voyance et divination"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/cosmic_32.jpg"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/DSCN1583.jpg"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Sandrine Marquet - Divinatrice & tireuse de cartes"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    # hidedesignbyline = true

    [params.meta]
        keywords = "tarot, future, voyance, fortune, divination, prediction, prophecy, magic, sortilege, misticism"


    
    
